#!/usr/bin/env python3
"""Stdlib-only stack supervisor for llama-conductor.

Design goals:
- zero third-party runtime dependencies
- non-interactive normal launch path
- explicit first-run setup via --setup
- JSON-lines logging for ops/observability
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import signal
import socket
import subprocess
import sys
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple
from urllib.error import URLError
from urllib.request import urlopen
from urllib.parse import urlparse


EXIT_OK = 0
EXIT_UNEXPECTED = 1
EXIT_CONFIG = 2
EXIT_START_FAIL = 3
EXIT_HEALTH_TIMEOUT = 4


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def log(event: str, status: str, **fields: Any) -> None:
    payload = {"t": _now_iso(), "event": event, "status": status}
    payload.update(fields)
    try:
        print(json.dumps(payload, ensure_ascii=False), flush=True)
    except Exception:
        print(
            f'{{"t":"{_now_iso()}","event":"{event}","status":"{status}"}}',
            flush=True,
        )


def _strip_comment(line: str) -> str:
    in_single = False
    in_double = False
    out: List[str] = []
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == "'" and not in_double:
            in_single = not in_single
            out.append(ch)
        elif ch == '"' and not in_single:
            in_double = not in_double
            out.append(ch)
        elif ch == "#" and not in_single and not in_double:
            break
        else:
            out.append(ch)
        i += 1
    return "".join(out).rstrip()


def _parse_scalar(raw: str) -> Any:
    s = str(raw or "").strip()
    if s == "":
        return ""
    low = s.lower()
    if low in {"true", "yes", "on"}:
        return True
    if low in {"false", "no", "off"}:
        return False
    if low in {"null", "none", "~"}:
        return None
    if (s.startswith('"') and s.endswith('"')) or (s.startswith("'") and s.endswith("'")):
        return s[1:-1]
    try:
        if any(ch in s for ch in (".", "e", "E")):
            return float(s)
        return int(s)
    except Exception:
        return s


def _load_simple_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(str(path))
    raw_lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    root: Dict[str, Any] = {}
    stack: List[Tuple[int, Any]] = [(-1, root)]

    i = 0
    while i < len(raw_lines):
        original = raw_lines[i]
        line = _strip_comment(original)
        if not line.strip():
            i += 1
            continue

        indent = len(line) - len(line.lstrip(" "))
        content = line[indent:]
        while stack and indent <= stack[-1][0]:
            stack.pop()
        if not stack:
            stack = [(-1, root)]
        parent = stack[-1][1]

        if content.startswith("- "):
            item = _parse_scalar(content[2:].strip())
            if isinstance(parent, list):
                parent.append(item)
            i += 1
            continue

        if ":" not in content:
            i += 1
            continue

        key, rest = content.split(":", 1)
        key = key.strip()
        if i == 0:
            key = key.lstrip("\ufeff")
        rest = rest.strip()

        if isinstance(parent, list):
            i += 1
            continue

        if rest != "":
            parent[key] = _parse_scalar(rest)
            i += 1
            continue

        child: Any = {}
        j = i + 1
        while j < len(raw_lines):
            nline = _strip_comment(raw_lines[j])
            if not nline.strip():
                j += 1
                continue
            nindent = len(nline) - len(nline.lstrip(" "))
            ncontent = nline[nindent:]
            if nindent <= indent:
                child = {}
                break
            child = [] if ncontent.startswith("- ") else {}
            break

        parent[key] = child
        stack.append((indent, child))
        i += 1

    return root


def _yaml_quote(value: str) -> str:
    s = str(value)
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _dump_stack_local_yaml(data: Dict[str, Any]) -> str:
    lines: List[str] = [
        "## Generated by: python tools/start_stack.py --setup",
        "## This file is read by tools/start_stack.py at launch time.",
        "## Keep values blank to inherit from llama_conductor/router_config.yaml.",
    ]

    section_comments: Dict[str, List[str]] = {
        "version": [
            "## Schema version for this local file.",
        ],
        "paths": [
            "## Optional local path overrides. Empty means inherit from router_config.yaml.",
        ],
        "qdrant": [
            "## Optional Qdrant launcher settings. Set enabled: true to auto-launch Qdrant.",
            "## launch_mode: 'direct' (default) or 'cmd_start_min' (Windows parity with old batch behavior).",
        ],
        "metrics": [
            "## Optional supervisor metrics endpoint (Prometheus text format). Default is off.",
        ],
        "notes": [
            "## Auto-populated informational snapshot from router_config.yaml at setup time.",
            "## notes.* is informational only. You may edit paths/qdrant/metrics manually.",
            "## Rerun --setup only if you want notes.* refreshed.",
        ],
    }

    def emit(k: str, v: Any, ind: int) -> None:
        pad = " " * ind
        if isinstance(v, dict):
            lines.append(f"{pad}{k}:")
            for ck, cv in v.items():
                emit(str(ck), cv, ind + 2)
            return
        if isinstance(v, bool):
            lines.append(f"{pad}{k}: {'true' if v else 'false'}")
            return
        if v is None:
            lines.append(f"{pad}{k}: null")
            return
        if isinstance(v, (int, float)):
            lines.append(f"{pad}{k}: {v}")
            return
        lines.append(f"{pad}{k}: {_yaml_quote(str(v))}")

    for idx, (key, value) in enumerate(data.items()):
        if idx > 0:
            lines.append("")
        if str(key) in section_comments:
            for c in section_comments[str(key)]:
                lines.append(c)
        emit(str(key), value, 0)
    return "\n".join(lines).rstrip() + "\n"

def _get_path(mapping: Mapping[str, Any], dotted: str, default: Any = None) -> Any:
    cur: Any = mapping
    for part in dotted.split("."):
        if not isinstance(cur, Mapping) or part not in cur:
            return default
        cur = cur[part]
    return cur


def _as_bool(v: Any, default: bool = False) -> bool:
    if isinstance(v, bool):
        return v
    if v is None:
        return default
    return str(v).strip().lower() in {"1", "true", "yes", "on"}


def _as_int(v: Any, default: int) -> int:
    try:
        return int(v)
    except Exception:
        return int(default)


def _as_float(v: Any, default: float) -> float:
    try:
        return float(v)
    except Exception:
        return float(default)


@dataclass
class Resolved:
    repo_root: Path
    router_config: Path
    local_config: Path
    provider: str
    router_host: str
    router_port: int
    llama_host: str
    llama_port: int
    llama_exe: str
    models_dir: str
    models_preset_path: str
    llama_ctx: int
    llama_threads: int
    llama_threads_batch: int
    llama_keep: int
    llama_batch: int
    llama_ubatch: int
    llama_parallel: int
    shim_enabled: bool
    shim_host: str
    shim_port: int
    shim_inject_ui: bool
    shim_auth_user: str
    shim_auth_password: str
    shim_force_vision: bool
    shim_render_mode: str
    shim_ui_model_alias: str
    shim_router_model_id: str
    ready_timeout_s: float
    auto_clean: bool
    qdrant_enabled: bool
    qdrant_bin: str
    qdrant_host: str
    qdrant_port: int
    qdrant_health_url: str
    qdrant_launch_mode: str
    metrics_enabled: bool
    metrics_host: str
    metrics_port: int


def _resolve_settings(repo_root: Path, router_cfg: Dict[str, Any], local_cfg: Dict[str, Any]) -> Resolved:
    provider = str(_get_path(router_cfg, "backend.provider", "llama_cpp") or "llama_cpp").strip().lower()
    models_dir_override = str(_get_path(local_cfg, "paths.models_dir_override", "") or "").strip()
    llama_exe_override = str(_get_path(local_cfg, "paths.llama_exe_override", "") or "").strip()

    models_dir = models_dir_override or str(_get_path(router_cfg, "backend.llama_cpp.models_dir", "") or "")
    llama_exe = llama_exe_override or str(_get_path(router_cfg, "backend.llama_cpp.exe_path", "") or "")
    models_preset_path = str(_get_path(router_cfg, "backend.llama_cpp.models_preset_path", "") or "").strip()
    if not models_preset_path and models_dir:
        models_preset_path = str(Path(models_dir) / "llama-router-models.ini")

    qdrant_port = _as_int(_get_path(local_cfg, "qdrant.port", _get_path(router_cfg, "rag.qdrant_port", 6333)), 6333)
    return Resolved(
        repo_root=repo_root,
        router_config=repo_root / "llama_conductor" / "router_config.yaml",
        local_config=repo_root / "stack.local.yaml",
        provider=provider,
        router_host=str(_get_path(router_cfg, "launcher.router_host", "0.0.0.0") or "0.0.0.0"),
        router_port=_as_int(_get_path(router_cfg, "port", 9000), 9000),
        llama_host=str(_get_path(router_cfg, "backend.llama_cpp.host", "0.0.0.0") or "0.0.0.0"),
        llama_port=_as_int(_get_path(router_cfg, "backend.llama_cpp.port", _get_path(router_cfg, "backend.local_llama_port", 8010)), 8010),
        llama_exe=llama_exe,
        models_dir=models_dir,
        models_preset_path=models_preset_path,
        llama_ctx=_as_int(_get_path(router_cfg, "backend.llama_cpp.ctx_size", 8192), 8192),
        llama_threads=_as_int(_get_path(router_cfg, "backend.llama_cpp.threads", 12), 12),
        llama_threads_batch=_as_int(_get_path(router_cfg, "backend.llama_cpp.threads_batch", 12), 12),
        llama_keep=_as_int(_get_path(router_cfg, "backend.llama_cpp.keep", 96), 96),
        llama_batch=_as_int(_get_path(router_cfg, "backend.llama_cpp.batch_size", 512), 512),
        llama_ubatch=_as_int(_get_path(router_cfg, "backend.llama_cpp.ubatch_size", 256), 256),
        llama_parallel=_as_int(_get_path(router_cfg, "backend.llama_cpp.parallel", 1), 1),
        shim_enabled=_as_bool(_get_path(router_cfg, "frontend.shim.enabled", True), True),
        shim_host=str(_get_path(router_cfg, "frontend.shim.host", "0.0.0.0") or "0.0.0.0"),
        shim_port=_as_int(_get_path(router_cfg, "frontend.shim.port", 8088), 8088),
        shim_inject_ui=_as_bool(_get_path(router_cfg, "frontend.shim.inject_ui", True), True),
        shim_auth_user=str(_get_path(router_cfg, "frontend.shim.auth_user", "") or ""),
        shim_auth_password=str(_get_path(router_cfg, "frontend.shim.auth_password", "") or ""),
        shim_force_vision=_as_bool(_get_path(router_cfg, "frontend.shim.force_vision", False), False),
        shim_render_mode=str(_get_path(router_cfg, "frontend.shim.render_mode", "stream") or "stream"),
        shim_ui_model_alias=str(_get_path(router_cfg, "frontend.shim.ui_model_alias", "") or ""),
        shim_router_model_id=str(_get_path(router_cfg, "frontend.shim.router_model_id", "moa-router") or "moa-router"),
        ready_timeout_s=_as_float(_get_path(router_cfg, "launcher.ready_timeout_s", 22.0), 22.0),
        auto_clean=_as_bool(_get_path(router_cfg, "launcher.auto_clean_before_start", True), True),
        qdrant_enabled=_as_bool(_get_path(local_cfg, "qdrant.enabled", False), False),
        qdrant_bin=str(_get_path(local_cfg, "paths.qdrant_bin", "") or ""),
        qdrant_host=str(_get_path(local_cfg, "qdrant.host", "127.0.0.1") or "127.0.0.1"),
        qdrant_port=qdrant_port,
        qdrant_health_url=str(_get_path(local_cfg, "qdrant.health_url", f"http://127.0.0.1:{qdrant_port}/readyz") or f"http://127.0.0.1:{qdrant_port}/readyz"),
        qdrant_launch_mode=str(_get_path(local_cfg, "qdrant.launch_mode", "direct") or "direct").strip().lower(),
        metrics_enabled=_as_bool(_get_path(local_cfg, "metrics.enabled", False), False),
        metrics_host=str(_get_path(local_cfg, "metrics.host", "127.0.0.1") or "127.0.0.1"),
        metrics_port=_as_int(_get_path(local_cfg, "metrics.port", 9919), 9919),
    )


def _detect_qdrant_binary() -> str:
    if os.name == "nt":
        try:
            proc = subprocess.run(["where", "qdrant.exe"], capture_output=True, text=True, check=False)
            if proc.returncode == 0:
                line = (proc.stdout or "").splitlines()[0].strip()
                if line:
                    return line
        except Exception:
            return ""
    else:
        p = shutil.which("qdrant")
        return p or ""
    return ""


def _prompt(text: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{text}{suffix}: ").strip()
    except EOFError:
        return default
    return val if val else default


def _run_setup(router_cfg: Dict[str, Any], local_cfg_path: Path, non_interactive: bool = False) -> int:
    log("setup", "start", local_config=str(local_cfg_path))
    models_dir_cfg = str(_get_path(router_cfg, "backend.llama_cpp.models_dir", "") or "")
    llama_exe_cfg = str(_get_path(router_cfg, "backend.llama_cpp.exe_path", "") or "")
    qdrant_guess = _detect_qdrant_binary()

    if non_interactive:
        models_dir_override = ""
        llama_exe_override = ""
        qdrant_enabled = False
        qdrant_bin = ""
    else:
        print("\n[setup] First-run local launcher config\n")
        print("Leave blank to inherit from router_config.yaml where applicable.\n")
        models_dir_override = _prompt("Models dir override (optional)", "")
        llama_exe_override = _prompt("llama-server exe override (optional)", "")
        qdrant_enable_raw = _prompt("Enable Qdrant launch? (y/N)", "N").strip().lower()
        qdrant_enabled = qdrant_enable_raw in {"y", "yes", "1", "true", "on"}
        qdrant_bin = ""
        if qdrant_enabled:
            qdrant_bin = _prompt("Qdrant binary path", qdrant_guess)

    qport = _as_int(_get_path(router_cfg, "rag.qdrant_port", 6333), 6333)
    data: Dict[str, Any] = {
        "version": 1,
        "paths": {
            "models_dir_override": models_dir_override,
            "llama_exe_override": llama_exe_override,
            "qdrant_bin": qdrant_bin,
        },
        "qdrant": {
            "enabled": bool(qdrant_enabled),
            "host": "127.0.0.1",
            "port": qport,
            "health_url": f"http://127.0.0.1:{qport}/readyz",
            "launch_mode": "direct",
        },
        "metrics": {
            "enabled": False,
            "host": "127.0.0.1",
            "port": 9919,
        },
        "notes": {
            "models_dir_inherited_from_router_config": models_dir_cfg,
            "llama_exe_inherited_from_router_config": llama_exe_cfg,
        },
    }
    local_cfg_path.write_text(_dump_stack_local_yaml(data), encoding="utf-8", newline="\n")
    log("setup", "ok", wrote=str(local_cfg_path), qdrant_enabled=qdrant_enabled, mode=("auto" if non_interactive else "interactive"))
    return EXIT_OK

def _port_open(port: int, host: str = "127.0.0.1") -> bool:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.5)
    try:
        return sock.connect_ex((host, int(port))) == 0
    except Exception:
        return False
    finally:
        try:
            sock.close()
        except Exception:
            pass


def _find_pids_on_port(port: int) -> List[int]:
    pids: List[int] = []
    try:
        if os.name == "nt":
            proc = subprocess.run(["netstat", "-ano", "-p", "tcp"], capture_output=True, text=True, check=False)
            if proc.returncode != 0:
                return []
            needle = f":{int(port)}"
            for ln in (proc.stdout or "").splitlines():
                s = ln.strip()
                if not s or "LISTENING" not in s.upper():
                    continue
                if needle not in s:
                    continue
                parts = s.split()
                if len(parts) >= 5:
                    try:
                        pid = int(parts[-1])
                        if pid > 0:
                            pids.append(pid)
                    except Exception:
                        continue
        else:
            proc = subprocess.run(["ss", "-ltnp", f"sport = :{int(port)}"], capture_output=True, text=True, check=False)
            if proc.returncode != 0:
                return []
            for ln in (proc.stdout or "").splitlines():
                for token in ln.split():
                    if "pid=" in token:
                        start = token.find("pid=")
                        if start >= 0:
                            frag = token[start + 4 :]
                            digits = ""
                            for ch in frag:
                                if ch.isdigit():
                                    digits += ch
                                else:
                                    break
                            if digits:
                                pids.append(int(digits))
    except Exception:
        return []
    return sorted(set(pids))


def _kill_pid(pid: int) -> bool:
    try:
        if os.name == "nt":
            proc = subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"], capture_output=True, text=True, check=False)
            return proc.returncode == 0
        os.kill(pid, signal.SIGTERM)
        return True
    except Exception:
        return False


def _wait_port_free(port: int, timeout_s: float) -> bool:
    deadline = time.monotonic() + max(1.0, float(timeout_s))
    while time.monotonic() < deadline:
        if not _port_open(port):
            return True
        time.sleep(0.25)
    return not _port_open(port)


def _preclean_port(label: str, port: int) -> bool:
    pids = _find_pids_on_port(port)
    if pids:
        log("preclean", "info", label=label, port=port, pids=pids)
    for pid in pids:
        ok = _kill_pid(pid)
        log("preclean.kill", "ok" if ok else "warn", port=port, pid=pid)
    ok_free = _wait_port_free(port, timeout_s=8.0)
    log("preclean.wait_free", "ok" if ok_free else "fail", label=label, port=port)
    return ok_free


def _http_ready(url: str, timeout_s: float = 2.0, must_contain: str = "") -> bool:
    try:
        with urlopen(url, timeout=timeout_s) as resp:  # nosec B310 local probes only
            status = int(getattr(resp, "status", 0))
            if status < 200 or status >= 400:
                return False
            if must_contain:
                body = resp.read(4096).decode("utf-8", errors="ignore")
                return must_contain in body
            return True
    except URLError:
        return False
    except Exception:
        return False


def _wait_http(url: str, label: str, timeout_s: float, must_contain: str = "") -> bool:
    deadline = time.monotonic() + max(1.0, float(timeout_s))
    delay = 0.35
    while time.monotonic() < deadline:
        if _http_ready(url, timeout_s=min(2.0, delay + 0.5), must_contain=must_contain):
            log("health", "ok", label=label, url=url)
            return True
        time.sleep(delay)
        delay = min(2.0, delay * 1.4)
    log("health", "fail", label=label, url=url, timeout_s=timeout_s)
    return False


def _wait_qdrant_http(primary_url: str, timeout_s: float) -> bool:
    urls: List[str] = [str(primary_url or "").strip()]
    try:
        p = urlparse(urls[0])
        if p.scheme and p.netloc:
            root = f"{p.scheme}://{p.netloc}/"
            if root not in urls:
                urls.append(root)
    except Exception:
        pass

    deadline = time.monotonic() + max(1.0, float(timeout_s))
    delay = 0.35
    while time.monotonic() < deadline:
        for u in urls:
            if u and _http_ready(u, timeout_s=min(2.0, delay + 0.5)):
                log("health", "ok", label="qdrant", url=u)
                return True
        time.sleep(delay)
        delay = min(2.0, delay * 1.4)
    log("health", "fail", label="qdrant", url=urls[0] if urls else "", timeout_s=timeout_s)
    return False


class _MetricsState:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self.service_up: Dict[str, int] = {}

    def set(self, service: str, up: bool) -> None:
        with self._lock:
            self.service_up[service] = 1 if up else 0

    def render_prom(self) -> str:
        with self._lock:
            lines = [
                "# HELP service_up 1 if service considered healthy by supervisor",
                "# TYPE service_up gauge",
            ]
            for name in sorted(self.service_up.keys()):
                lines.append(f'service_up{{service="{name}"}} {int(self.service_up[name])}')
            return "\n".join(lines) + "\n"


class _MetricsHandler(BaseHTTPRequestHandler):
    state: _MetricsState = _MetricsState()

    def do_GET(self) -> None:  # noqa: N802
        if self.path not in {"/metrics", "/"}:
            self.send_response(404)
            self.end_headers()
            return
        payload = self.state.render_prom().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt: str, *args: Any) -> None:
        return


def _start_metrics_server(host: str, port: int, state: _MetricsState) -> HTTPServer:
    _MetricsHandler.state = state
    server = HTTPServer((host, int(port)), _MetricsHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server


def _spawn(
    cmd: List[str],
    cwd: Path,
    env: Dict[str, str],
    label: str,
) -> Optional[subprocess.Popen]:
    log("spawn", "info", label=label, cmd=cmd, cwd=str(cwd))
    kwargs: Dict[str, Any] = {"cwd": str(cwd), "env": env}
    try:
        if os.name == "nt":
            flags = 0
            flags |= getattr(subprocess, "CREATE_NEW_CONSOLE", 0)
            flags |= getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
            kwargs["creationflags"] = flags
        else:
            kwargs["start_new_session"] = True
        proc = subprocess.Popen(cmd, **kwargs)  # noqa: S603
        log("spawn", "ok", label=label, pid=int(getattr(proc, "pid", 0) or 0))
        return proc
    except Exception as e:
        log("spawn", "fail", label=label, error=str(e))
        return None


def _generate_models_preset(py_exe: str, repo_root: Path, cfg_path: Path, out_path: Path, ctx_size: int) -> bool:
    script = repo_root / "llama_conductor" / "generate_models_preset.py"
    if not script.exists():
        log("preset", "fail", reason="missing generator", script=str(script))
        return False
    cmd = [py_exe, str(script), "--config", str(cfg_path), "--out", str(out_path), "--ctx-size", str(int(ctx_size))]
    try:
        proc = subprocess.run(cmd, cwd=str(repo_root), check=False)  # noqa: S603
    except Exception as e:
        log("preset", "fail", error=str(e))
        return False
    ok = proc.returncode == 0 and out_path.exists()
    log("preset", "ok" if ok else "fail", returncode=int(proc.returncode), out=str(out_path))
    return ok


def _ensure_local_config(path: Path) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
    if not path.exists():
        return None, f"missing {path}. Run: python tools/start_stack.py --setup"
    try:
        cfg = _load_simple_yaml(path)
    except Exception as e:
        return None, f"invalid {path}: {e}. Run: python tools/start_stack.py --setup"
    if _as_int(_get_path(cfg, "version", 0), 0) < 1:
        return None, f"incomplete {path} (version missing). Run: python tools/start_stack.py --setup"
    return cfg, None

def _run_doctor(res: Resolved) -> int:
    log("doctor", "ok", platform=platform.platform(), python=sys.executable)
    log(
        "doctor.resolved",
        "ok",
        provider=res.provider,
        router_host=res.router_host,
        router_port=res.router_port,
        llama_host=res.llama_host,
        llama_port=res.llama_port,
        llama_exe=res.llama_exe,
        models_dir=res.models_dir,
        models_preset_path=res.models_preset_path,
        shim_enabled=res.shim_enabled,
        shim_host=res.shim_host,
        shim_port=res.shim_port,
        qdrant_enabled=res.qdrant_enabled,
        qdrant_bin=res.qdrant_bin,
        qdrant_health_url=res.qdrant_health_url,
        qdrant_launch_mode=res.qdrant_launch_mode,
        metrics_enabled=res.metrics_enabled,
        metrics_host=res.metrics_host,
        metrics_port=res.metrics_port,
    )
    return EXIT_OK


def _run_launch(res: Resolved) -> int:
    state = _MetricsState()
    metrics_server: Optional[HTTPServer] = None
    if res.metrics_enabled:
        try:
            metrics_server = _start_metrics_server(res.metrics_host, res.metrics_port, state)
            log("metrics", "ok", host=res.metrics_host, port=res.metrics_port)
        except Exception as e:
            log("metrics", "fail", error=str(e), host=res.metrics_host, port=res.metrics_port)

    if res.auto_clean:
        ports: List[Tuple[str, int]] = []
        if res.provider == "llama_cpp":
            ports.append(("upstream", res.llama_port))
        ports.append(("router", res.router_port))
        if res.shim_enabled:
            ports.append(("shim", res.shim_port))
        if res.qdrant_enabled:
            ports.append(("qdrant", res.qdrant_port))
        for label, port in ports:
            if not _preclean_port(label, port):
                return EXIT_START_FAIL

    py = sys.executable
    env = dict(os.environ)

    # Qdrant optional.
    if res.qdrant_enabled:
        if not res.qdrant_bin:
            log("qdrant", "warn", message="Qdrant not configured — ##mentats/Vault paths will be unavailable.")
            state.set("qdrant", False)
        elif not Path(res.qdrant_bin).exists():
            log("qdrant", "warn", message="Qdrant binary not found — ##mentats/Vault paths will be unavailable.", path=res.qdrant_bin)
            state.set("qdrant", False)
        else:
            qmode = str(res.qdrant_launch_mode or "direct").strip().lower()
            if os.name == "nt" and qmode == "cmd_start_min":
                qexe_full = str(Path(res.qdrant_bin))
                qproc = _spawn(
                    ["cmd.exe", "/c", f'start "" /min "{qexe_full}"'],
                    cwd=Path(res.qdrant_bin).parent,
                    env=env,
                    label="qdrant",
                )
                log("qdrant", "info", launch_mode="cmd_start_min", cwd=str(Path(res.qdrant_bin).parent), exe=qexe_full)
            else:
                qproc = _spawn([res.qdrant_bin], cwd=Path(res.qdrant_bin).parent, env=env, label="qdrant")
                log("qdrant", "info", launch_mode="direct", path=res.qdrant_bin)
            if qproc is None:
                return EXIT_START_FAIL
            qok = _wait_qdrant_http(res.qdrant_health_url, timeout_s=max(5.0, res.ready_timeout_s * 0.8))
            state.set("qdrant", qok)
            if not qok:
                log("qdrant", "warn", message="Qdrant launched but health check timed out; continuing.")

    if res.provider == "llama_cpp":
        if not res.llama_exe:
            log("config", "fail", reason="llama_cpp requires backend.llama_cpp.exe_path or stack.local override")
            return EXIT_CONFIG
        if not Path(res.llama_exe).exists():
            log("config", "fail", reason="llama_cpp exe path not found", path=res.llama_exe)
            return EXIT_CONFIG
        if not res.models_dir:
            log("config", "fail", reason="llama_cpp requires backend.llama_cpp.models_dir or stack.local override")
            return EXIT_CONFIG
        if not Path(res.models_dir).exists():
            log("config", "fail", reason="models_dir path not found", path=res.models_dir)
            return EXIT_CONFIG
        if not res.models_preset_path:
            log("config", "fail", reason="models_preset_path unresolved")
            return EXIT_CONFIG
        if not _generate_models_preset(py, res.repo_root, res.router_config, Path(res.models_preset_path), res.llama_ctx):
            return EXIT_START_FAIL

        llama_cmd = [
            res.llama_exe,
            "--models-dir", res.models_dir,
            "--models-preset", res.models_preset_path,
            "-t", str(res.llama_threads),
            "--threads-batch", str(res.llama_threads_batch),
            "-c", str(res.llama_ctx),
            "--keep", str(res.llama_keep),
            "--context-shift",
            "-b", str(res.llama_batch),
            "-ub", str(res.llama_ubatch),
            "--metrics",
            "--parallel", str(res.llama_parallel),
            "--port", str(res.llama_port),
            "--host", res.llama_host,
        ]
        if _spawn(llama_cmd, cwd=Path(res.llama_exe).parent, env=env, label="upstream") is None:
            return EXIT_START_FAIL
        up_ok = _wait_http(f"http://127.0.0.1:{res.llama_port}/v1/models", "upstream", timeout_s=res.ready_timeout_s)
        state.set("upstream", up_ok)
        if not up_ok:
            return EXIT_HEALTH_TIMEOUT

    router_cli = res.repo_root / "llama_conductor_cli.py"
    if not router_cli.exists():
        log("config", "fail", reason="missing llama_conductor_cli.py", path=str(router_cli))
        return EXIT_CONFIG
    if _spawn(
        [py, str(router_cli), "serve", "--host", res.router_host, "--port", str(res.router_port)],
        cwd=res.repo_root,
        env=env,
        label="router",
    ) is None:
        return EXIT_START_FAIL
    router_ok = _wait_http(f"http://127.0.0.1:{res.router_port}/v1/models", "router", timeout_s=res.ready_timeout_s)
    state.set("router", router_ok)
    if not router_ok:
        return EXIT_HEALTH_TIMEOUT

    if res.shim_enabled:
        shim_py = res.repo_root / "llama_conductor" / "shim" / "shim_server.py"
        if not shim_py.exists():
            log("config", "fail", reason="shim enabled but shim_server.py missing", path=str(shim_py))
            return EXIT_CONFIG
        shim_env = dict(env)
        shim_env["MOA_CHAT_HOST"] = res.shim_host
        shim_env["MOA_CHAT_PORT"] = str(res.shim_port)
        shim_env["MOA_CHAT_LLAMASERVER_URL"] = f"http://127.0.0.1:{res.llama_port}"
        shim_env["MOA_CHAT_ROUTER_URL"] = f"http://127.0.0.1:{res.router_port}"
        shim_env["MOA_CHAT_INJECT_UI"] = "1" if res.shim_inject_ui else "0"
        shim_env["MOA_CHAT_AUTH_USER"] = res.shim_auth_user
        shim_env["MOA_CHAT_PASSWORD"] = res.shim_auth_password
        shim_env["MOA_CHAT_FORCE_VISION"] = "1" if res.shim_force_vision else "0"
        shim_env["MOA_CHAT_RENDER_MODE"] = res.shim_render_mode
        shim_env["MOA_CHAT_UI_MODEL_ALIAS"] = res.shim_ui_model_alias
        shim_env["MOA_CHAT_ROUTER_MODEL_ID"] = res.shim_router_model_id
        if _spawn(
            [py, str(shim_py)],
            cwd=shim_py.parent,
            env=shim_env,
            label="shim",
        ) is None:
            return EXIT_START_FAIL
        shim_ok = _wait_http(f"http://127.0.0.1:{res.shim_port}/shim/healthz", "shim", timeout_s=res.ready_timeout_s, must_contain='"ok":true')
        state.set("shim", shim_ok)
        if not shim_ok:
            return EXIT_HEALTH_TIMEOUT

    log(
        "launch",
        "ok",
        provider=res.provider,
        upstream=(f"http://127.0.0.1:{res.llama_port}" if res.provider == "llama_cpp" else "external"),
        router=f"http://127.0.0.1:{res.router_port}",
        shim=(f"http://127.0.0.1:{res.shim_port}" if res.shim_enabled else "disabled"),
    )

    if metrics_server is not None:
        log("metrics", "info", message="metrics enabled; supervisor staying alive", endpoint=f"http://{res.metrics_host}:{res.metrics_port}/metrics")
        try:
            while True:
                time.sleep(1.0)
        except KeyboardInterrupt:
            log("metrics", "info", message="shutdown requested")
            try:
                metrics_server.shutdown()
            except Exception:
                pass

    return EXIT_OK


def _build_parser() -> argparse.ArgumentParser:
    repo_root = Path(__file__).resolve().parents[1]
    p = argparse.ArgumentParser(description="stdlib-only launcher for llama-conductor stack")
    p.add_argument("--setup", action="store_true", help="interactive first-run setup; writes stack.local.yaml")
    p.add_argument("--doctor", action="store_true", help="print resolved launch configuration (JSONL)")
    p.add_argument("--config", default=str(repo_root / "llama_conductor" / "router_config.yaml"), help="router config path")
    p.add_argument("--local-config", default=str(repo_root / "stack.local.yaml"), help="local launcher config path")
    return p


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = _build_parser().parse_args(list(argv) if argv is not None else None)
    try:
        repo_root = Path(__file__).resolve().parents[1]
        router_cfg_path = Path(args.config).resolve()
        local_cfg_path = Path(args.local_config).resolve()

        if not router_cfg_path.exists():
            log("config", "fail", reason="router_config.yaml not found", path=str(router_cfg_path))
            return EXIT_CONFIG
        router_cfg = _load_simple_yaml(router_cfg_path)

        if args.setup:
            return _run_setup(router_cfg, local_cfg_path)

        local_cfg, local_err = _ensure_local_config(local_cfg_path)
        if local_err:
            if str(local_err).startswith("missing "):
                log("setup", "info", message="local config missing; auto-running setup with defaults", path=str(local_cfg_path))
                rc = _run_setup(router_cfg, local_cfg_path, non_interactive=True)
                if rc != EXIT_OK:
                    return EXIT_CONFIG
                local_cfg, local_err = _ensure_local_config(local_cfg_path)
            if local_err:
                log("config", "fail", reason=local_err)
                return EXIT_CONFIG
        assert local_cfg is not None
        resolved = _resolve_settings(repo_root, router_cfg, local_cfg)

        if args.doctor:
            return _run_doctor(resolved)
        return _run_launch(resolved)
    except KeyboardInterrupt:
        log("main", "warn", message="interrupted")
        return EXIT_UNEXPECTED
    except Exception as e:
        log("main", "fail", error=str(e))
        return EXIT_UNEXPECTED


if __name__ == "__main__":
    raise SystemExit(main())
